name: .NET Server Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'

      - name: Build Server.Player.Domain
        working-directory: src/Server/Server.Player.Domain
        run: dotnet build --configuration Release

      - name: Build Server.User.Domain
        working-directory: src/Server/Server.User.Domain
        run: dotnet build --configuration Release

      - name: Build Server.Api
        working-directory: src/Server/Server.Api
        run: dotnet build --configuration Release
