name: .NET Server Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Server/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Server/**'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'
        
      - name: Build Module.Player.Api
        working-directory: src/Server/Modules/Player/Module.Player.Api
        run: dotnet build --configuration Release

      - name: Build Server.Api
        working-directory: src/Server/Server.Api
        run: dotnet build --configuration Release
