name: .NET WPF Application Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-wpf:
    if: contains(join(github.event.commits.*.message, ' '), 'client') || (github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'client'))
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'

      - name: Build WPF Client
        run: dotnet build src/Client/WpfClient/WpfClient.csproj --configuration Release